language: php

php:
  - 5.3
  
env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer require symfony/validator:${SYMFONY_VERSION} --no-update
  - composer require symfony/doctrine-bridge:${SYMFONY_VERSION} --no-update
  - composer require doctrine/orm:2.4.* --no-update
  - composer require doctrine/data-fixtures:1.0.* --no-update
  - composer update --dev

script: phpunit
