language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/validator:${SYMFONY_VERSION} --no-update
    - composer require symfony/doctrine-bridge:${SYMFONY_VERSION} --no-update
    - composer require doctrine/orm:2.4.* --no-update
    - composer require doctrine/data-fixtures:1.0.* --no-update
    - composer update --dev

script: phpunit
